// automatically generated by spin2cpp v3.9.23 on Tue Mar 19 08:17:22 2019
// command line: spin2cpp --p2 --ccode pasmtest.spin 

//
// simple ASM demo
//
//
// this simple program runs in another COG and adds two numbers together
//
// it is passed a mailbox pointing to three long values:
//   mbox[0] = command; this is 1 to indicate we should do something
//             we set command to 0 when we are finished
//   mbox[1] = aval; we also write back the final result (aval+bval) here
//   mbox[2] = bval
//
#ifdef __riscv
#include "../lib/riscv.h"
#else
#include <propeller.h>
#endif
#include "pasmtest.h"

#define INLINE__ static inline
#define Yield__() __asm__ volatile( "" ::: "memory" )

static char dat[] = {
  0xf8, 0x25, 0x00, 0xf6, 0x12, 0x26, 0x00, 0xf6, 0x04, 0x24, 0x04, 0xf1, 0x12, 0x28, 0x00, 0xf6, 
  0x04, 0x24, 0x04, 0xf1, 0x12, 0x2a, 0x00, 0xf6, 0x13, 0x2c, 0x00, 0xfb, 0x00, 0x2c, 0x0c, 0xf2, 
  0xf4, 0xff, 0x9f, 0xad, 0x01, 0x2c, 0x0c, 0xf2, 0x10, 0x00, 0x90, 0x5d, 0x14, 0x2e, 0x00, 0xfb, 
  0x15, 0x30, 0x00, 0xfb, 0x18, 0x2e, 0x00, 0xf1, 0x14, 0x2e, 0x60, 0xfc, 0x13, 0x22, 0x60, 0xfc, 
  0xd4, 0xff, 0x9f, 0xfd, 0x00, 0x00, 0x00, 0x00, 
};
int32_t pasmtest_start(pasmtest *self)
{
//  self->cogx = cognew((int32_t)(((int32_t *)&dat[0])), (int32_t)(self->mbox)) + 1;
    self->cogx = coginit(3, (int32_t)(((int32_t *)&dat[0])), (int32_t)(self->mbox)) + 1;
  return self->cogx;
}

void pasmtest_stop(pasmtest *self)
{
  if (self->cogx >= 1) {
    cogstop(self->cogx - 1);
    self->cogx = 0;
  }
}

int32_t pasmtest_sum(pasmtest *self, int32_t a, int32_t b)
{
  // set up parameters
  // we must do this before triggering the command
  self->mbox[1] = a;
  self->mbox[2] = b;
  // now issue the command
  self->mbox[0] = 1;
  // wait for COG to finish
  while (self->mbox[0] != 0) {
    Yield__();
  }
  // and return result
  return self->mbox[1];
}

