// automatically generated by spin2cpp v3.9.23 on Tue Mar 19 08:17:22 2019
// command line: spin2cpp --p2 --ccode pasmtest.spin 

#ifndef pasmtest_Class_Defined__
#define pasmtest_Class_Defined__

#include <stdint.h>


typedef struct pasmtest {
// mailbox for communicating with COG
  volatile int32_t 	mbox[3];
// 1 + id of COG running our code (0 if stopped)
  volatile int32_t 	cogx;
} pasmtest;

  int32_t pasmtest_start(pasmtest *self);
  void pasmtest_stop(pasmtest *self);
  int32_t pasmtest_sum(pasmtest *self, int32_t a, int32_t b);
#endif
